name: 每日构建

on:
  schedule:
    # 每天 UTC 时间 00:00 运行（北京时间 08:00）
    - cron: '0 0 * * *'
  # 也允许手动触发
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './pure-mind-note/package-lock.json'

      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 安装 Ubuntu 依赖
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: 安装前端依赖
        run: cd pure-mind-note && npm ci

      - name: 缓存 Cargo 依赖
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            pure-mind-note/src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: 构建 Tauri 应用
        run: cd pure-mind-note && npm run tauri:build

      - name: 上传 Windows 构建
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pure-mind-note-windows
          path: |
            pure-mind-note/src-tauri/target/release/bundle/msi/*.msi
            pure-mind-note/src-tauri/target/release/bundle/nsis/*.exe

      - name: 上传 macOS 构建
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pure-mind-note-macos
          path: |
            pure-mind-note/src-tauri/target/release/bundle/dmg/*.dmg
            pure-mind-note/src-tauri/target/release/bundle/macos/*.app

      - name: 上传 Linux 构建
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pure-mind-note-linux
          path: |
            pure-mind-note/src-tauri/target/release/bundle/deb/*.deb
            pure-mind-note/src-tauri/target/release/bundle/appimage/*.AppImage 